#!/usr/bin/env bash
# build-cmsis-dsp.sh <core> [source-dir]
#
# Build CMSIS-DSP for one Cortex-M variant into
#     $CMSIS_DSP_DIR/lib/<core>/libCMSISDSP.a
# which is the layout find_cmsis_dsp() in embedded-common.cmake expects.
#
# Why this script exists: CMSIS-DSP ships NO toolchain file (its cmake/
# directory contains only CMSISDSPConfig.cmake.in) and has NO ARM_CPU or FPU
# CMake options — Source/CMakeLists.txt declares NEON, HELIUM, MVEF, MVEI,
# LOOPUNROLL, HOST, DISABLEFLOAT16 and friends, nothing else. The target
# architecture comes entirely from the toolchain file's compile flags, so a
# build that does not supply one produces a library for whatever the compiler
# defaults to. This generates the correct toolchain file per core.
#
# Cores prebuilt in the image: see the DSP_CORES build arg in the Dockerfile.
# Build any other at runtime:
#     build-cmsis-dsp cortex-m55
#     build-cmsis-dsp cortex-m4      # soft-float variant of M4

set -euo pipefail

CORE="${1:-}"
SRC="${2:-${CMSIS_DSP_DIR:-/opt/cmsis-dsp}}"
# CMSIS-DSP appends "/Include" to CMSISCORE itself, so this must be the Core
# directory, not its Include subdirectory.
CMSIS_CORE_DIR="${CMSIS_DIR:-/opt/cmsis}/CMSIS/Core"
CMSIS_CORE_INC="$CMSIS_CORE_DIR/Include"

if [ -z "$CORE" ]; then
    cat >&2 <<'USAGE'
Usage: build-cmsis-dsp <core> [source-dir]

Known cores:
  cortex-m0     cortex-m0plus   cortex-m3         (soft float)
  cortex-m4     cortex-m4f      (fpv4-sp-d16, hard)
  cortex-m7     cortex-m7f      (fpv5-d16, hard)
  cortex-m33    cortex-m33f     (fpv5-sp-d16, hard)  <- STM32WBA/U5/H5/L5
  cortex-m55    cortex-m85      (Helium)
USAGE
    exit 1
fi

# core name -> (mcpu, extra flags, disable float16)
case "$CORE" in
    cortex-m0)                 MCPU=cortex-m0;     FPFLAGS="-mfloat-abi=soft"; NOF16=ON ;;
    cortex-m0plus)             MCPU=cortex-m0plus; FPFLAGS="-mfloat-abi=soft"; NOF16=ON ;;
    cortex-m3)                 MCPU=cortex-m3;     FPFLAGS="-mfloat-abi=soft"; NOF16=ON ;;
    cortex-m4)                 MCPU=cortex-m4;     FPFLAGS="-mfloat-abi=soft"; NOF16=ON ;;
    cortex-m4f|cortex-m4-fpu)  MCPU=cortex-m4;     FPFLAGS="-mfpu=fpv4-sp-d16 -mfloat-abi=hard"; NOF16=OFF ;;
    cortex-m7)                 MCPU=cortex-m7;     FPFLAGS="-mfloat-abi=soft"; NOF16=ON ;;
    cortex-m7f)                MCPU=cortex-m7;     FPFLAGS="-mfpu=fpv5-d16 -mfloat-abi=hard"; NOF16=OFF ;;
    cortex-m33)                MCPU=cortex-m33+nofp; FPFLAGS="-mfloat-abi=soft"; NOF16=ON ;;
    cortex-m33f)               MCPU=cortex-m33;    FPFLAGS="-mfpu=fpv5-sp-d16 -mfloat-abi=hard"; NOF16=OFF ;;
    cortex-m55)                MCPU=cortex-m55;    FPFLAGS="-mfpu=auto -mfloat-abi=hard"; NOF16=OFF ;;
    cortex-m85)                MCPU=cortex-m85;    FPFLAGS="-mfpu=auto -mfloat-abi=hard"; NOF16=OFF ;;
    *)
        echo "ERROR: unknown core '$CORE'. Run with no arguments for the list." >&2
        exit 1
        ;;
esac

[ -d "$SRC" ] || { echo "ERROR: CMSIS-DSP source not found at $SRC" >&2; exit 1; }
[ -d "$CMSIS_CORE_INC" ] || { echo "ERROR: CMSIS core headers not found at $CMSIS_CORE_INC" >&2; exit 1; }

TC_DIR="$SRC/toolchains"
TC_FILE="$TC_DIR/${CORE}.cmake"
BUILD_DIR="$SRC/build-${CORE}"
OUT_DIR="$SRC/lib/${CORE}"

mkdir -p "$TC_DIR" "$OUT_DIR"

cat > "$TC_FILE" <<EOF
# Generated by build-cmsis-dsp.sh for ${CORE}. Do not edit by hand.
set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
set(CMAKE_AR           arm-none-eabi-ar)
set(CMAKE_RANLIB       arm-none-eabi-ranlib)

set(_ARCH_FLAGS "-mcpu=${MCPU} -mthumb ${FPFLAGS}")

set(CMAKE_C_FLAGS_INIT   "\${_ARCH_FLAGS} -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "\${_ARCH_FLAGS} -ffunction-sections -fdata-sections")
set(CMAKE_ASM_FLAGS_INIT "\${_ARCH_FLAGS}")

# CMSIS-DSP is a static library; a full link would need a linker script we do
# not have, so tell CMake's compiler probe to stop at the archive stage.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF

echo "== building CMSIS-DSP for ${CORE} (-mcpu=${MCPU} ${FPFLAGS}) =="

rm -rf "$BUILD_DIR"
# The repo root CMakeLists.txt is only a FetchContent redirection shim (no
# project()/cmake_minimum_required()), which CMake 4.x rejects outright.
# Source/ is the real entry point.
cmake -S "$SRC/Source" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$TC_FILE" \
    -DCMSISCORE="$CMSIS_CORE_DIR" \
    -DCMAKE_BUILD_TYPE=Release \
    -DDISABLEFLOAT16="$NOF16" \
    > "$BUILD_DIR.log" 2>&1 || { cat "$BUILD_DIR.log"; exit 1; }

cmake --build "$BUILD_DIR" --target CMSISDSP -j"$(nproc)" \
    >> "$BUILD_DIR.log" 2>&1 || { tail -60 "$BUILD_DIR.log"; exit 1; }

LIB="$(find "$BUILD_DIR" -name 'libCMSISDSP.a' -print -quit)"
[ -n "$LIB" ] || { echo "ERROR: libCMSISDSP.a not produced for ${CORE}" >&2; tail -40 "$BUILD_DIR.log"; exit 1; }

cp "$LIB" "$OUT_DIR/libCMSISDSP.a"

# Record what it was actually built for, so a mismatch is diagnosable later.
arm-none-eabi-readelf -A "$OUT_DIR/libCMSISDSP.a" 2>/dev/null \
    | grep -E 'Tag_CPU_name|Tag_CPU_arch|Tag_FP_arch|Tag_ABI_VFP_args' \
    | sort -u > "$OUT_DIR/build-attributes.txt" || true

cat > "$OUT_DIR/flags.cmake" <<EOF
# Flags this library was built with. A consumer MUST compile with the same
# -mcpu/-mfpu/-mfloat-abi or the link will be an architecture mismatch.
set(CMSIS_DSP_${CORE}_FLAGS "-mcpu=${MCPU} -mthumb ${FPFLAGS}")
EOF

rm -rf "$BUILD_DIR" "$BUILD_DIR.log"

echo "   -> $OUT_DIR/libCMSISDSP.a ($(du -h "$OUT_DIR/libCMSISDSP.a" | cut -f1))"
